// Hand-maintained — NOT generated by `npm run build:types`.
//
// tsc's JSDoc-based type pipeline (tsconfig.json's `include: ["src/**/*.js"]`)
// cannot process `.svelte` files, and `src/svelte/**` is excluded from that
// build entirely (see tsconfig.json). This is the one subpath export whose
// types are a manually maintained deviation from the "generated from JSDoc"
// story documented in the README's TypeScript section.
//
// Keep this in sync by hand whenever `PlayerOptions` (src/core/types.js)
// changes — the prop list below is a deliberate mirror of it, not a fresh
// design, so any new/renamed/removed option there should be reflected here
// in the same change.
import type { Component } from 'svelte';

export interface PlayerProps {
  url: string;
  controls?: boolean;
  light?: boolean;
  poster?: string;
  autoplay?: boolean;
  muted?: boolean;
  loop?: boolean;
  playbackRates?: number[];
  volume?: number;
  volumeKey?: string;
  videoSize?: 'cover' | 'contain' | 'fill';
  centerPlayButton?: boolean;
  loadingSpinner?: boolean;
  theme?: {
    primaryColor?: string;
    accentColor?: string;
    fontFamily?: string;
  };
  shield?: boolean;
  iframelyKey?: string;
  seo?: {
    name: string;
    description?: string;
    thumbnailUrl?: string;
    uploadDate?: string;
    durationSeconds?: number;
  };
  onEvent?: (event: { type: string; [key: string]: unknown }) => void;
  class?: string;
  style?: string;
}

export const Player: Component<PlayerProps>;
